spring:
  application:
    name: FeedSync
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

jwt:
  secret: IVy3wDtLYZBHxexS6cLusowwYOvP76iN